import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/saas", "routes/saas.tsx"),
  route("/blog", "routes/blog.tsx"),
  route("/blog/:slug", "routes/blogpost.tsx"),
  route("/resources", "routes/resources.tsx"),
  route("/contact", "routes/contact.tsx"),
  route("/projects", "routes/projects.tsx"),
  route("/projects/flink", "routes/projects/flink.tsx"),
  route("/projects/easybits", "routes/projects/easybits.tsx"),
  route("/projects/constructoken", "routes/projects/constructoken.tsx"),
  route("/projects/covalto", "routes/projects/covalto.tsx"),
  route("/projects/fixterorg", "routes/projects/fixterorg.tsx"),
  route("/projects/fixtergeek", "routes/projects/fixtergeek.tsx"),
  route("/projects/formmy", "routes/projects/formmy.tsx"),
  route("/projects/lastplay", "routes/projects/lastplay.tsx"),
  route("/projects/santander", "routes/projects/santander.tsx"),
  route("/projects/uicourse", "routes/projects/uicourse.tsx"),
  route("/projects/reform", "routes/projects/reformai.tsx"),
  route("/projects/realstate", "routes/projects/realstate.tsx"),
  route("/projects/denik", "routes/projects/denik.tsx"),
  route("/projects/epros", "routes/projects/epros.tsx"),
  route("/projects/azteca", "routes/projects/azteca.tsx"),
  route("/projects/potentiia", "routes/projects/potentiia.tsx"),
] satisfies RouteConfig;
